import { type Kysely, sql } from 'kysely';

import type { Database } from '@app/types';

export async function up(db: Kysely<Database>): Promise<void> {
  await db.transaction().execute(async (trx) => {
    await sql`
      INSERT INTO ingredient (name, color, kcal, degree, description, image, flavour, family)
      VALUES 
      ('Almond', 'Brown', 7, 0, 'Nutty and sweet', 'almond.jpg', 'sweet', 'fruit'),
      ('Anise', 'Brown', 22, 0, 'Licorice flavor', 'anise.jpg', 'spicy', 'spice'),
      ('Apple', 'Red', 52, 0, 'Crisp and sweet', 'apple.jpg', 'fruity', 'fruit'),
      ('Apricot', 'Orange', 48, 0, 'Sweet and velvety', 'apricot.jpg', 'fruity', 'fruit'),
      ('Avocado', 'Green', 160, 0, 'Creamy and rich', 'avocado.jpg', 'neutral', 'fruit'),
      ('Basil', 'Green', 3, 0, 'Aromatic herb', 'basil.jpg', 'herbaceous', 'herb'),
      ('Beer', 'Golden', 40, 5, 'Hoppy and malty', 'beer.jpg', 'bitter', 'alcohol'),
      ('Blackberry', 'Purple', 40, 0, 'Bold and juicy', 'blackberry.jpg', 'fruity', 'fruit'),
      ('Blueberry', 'Blue', 29, 0, 'Rich and sweet', 'blueberry.jpg', 'fruity', 'fruit'),
      ('Bourbon', 'Amber', 240, 40, 'Sweet and oaky', 'bourbon.jpg', 'sweet', 'alcohol'),
      ('Brandy', 'Amber', 65, 35, 'Fruity and warming', 'brandy.jpg', 'fruity', 'alcohol'),
      ('Cachaça', 'Clear', 50, 38, 'Sugarcane spirit', 'cachaca.jpg', 'other', 'alcohol'),
      ('Cantaloupe', 'Orange', 34, 0, 'Sweet and juicy', 'cantaloupe.jpg', 'fruity', 'fruit'),
      ('Caramel', 'Brown', 50, 0, 'Sweet and buttery', 'caramel.jpg', 'sweet', 'syrup'),
      ('Cauliflower', 'White', 25, 0, 'Mild and earthy', 'cauliflower.jpg', 'sweet', 'vegetable'),
      ('Champagne', 'Clear', 90, 12, 'Bubbly and celebratory', 'champagne.jpg', 'other', 'alcohol'),
      ('Cherry', 'Red', 50, 0, 'Sweet and tart', 'cherry.jpg', 'fruity', 'fruit'),
      ('Chervil', 'Green', 3, 0, 'Mild anise flavor', 'chervil.jpg', 'herbaceous', 'herb'),
      ('Chives', 'Green', 2, 0, 'Mild onion flavor', 'chives.jpg', 'salty', 'herb'),
      ('Chocolate', 'Brown', 230, 0, 'Rich and decadent', 'chocolate.jpg', 'sweet', 'other'),
      ('Cilantro', 'Green', 1, 0, 'Bright and citrusy', 'cilantro.jpg', 'herbaceous', 'herb'),
      ('Cinnamon', 'Brown', 6, 0, 'Warm and spicy', 'cinnamon.jpg', 'spicy', 'spice'),
      ('Clove', 'Brown', 21, 0, 'Strong and aromatic', 'clove.jpg', 'spicy', 'spice'),
      ('Coconut', 'White', 354, 0, 'Sweet and tropical', 'coconut.jpg', 'fruity', 'fruit'),
      ('Coffee', 'Brown', 2, 0, 'Bold and caffeinated', 'coffee.jpg', 'mixed', 'herb'),
      ('Coriander', 'Green', 2, 0, 'Citrusy and spicy', 'coriander.jpg', 'fresh', 'herb'),
      ('Corn', 'Yellow', 96, 0, 'Sweet and crunchy', 'corn.jpg', 'sweet', 'vegetable'),
      ('Cranberry', 'Red', 46, 0, 'Tart and tangy', 'cranberry.jpg', 'acidulous', 'fruit'),
      ('Cucumber', 'Green', 16, 0, 'Cool and crisp', 'cucumber.jpg', 'sweet', 'vegetable'),
      ('Currant', 'Red', 56, 0, 'Sweet and tangy', 'currant.jpg', 'acidulous', 'fruit'),
      ('Dill', 'Green', 2, 0, 'Grassy and tangy', 'dill.jpg', 'fresh', 'herb'),
      ('Dragon Fruit', 'Pink', 60, 0, 'Mild and refreshing', 'dragonfruit.jpg', 'sweet', 'fruit'),
      ('Eggplant', 'Purple', 25, 0, 'Mild and meaty', 'eggplant.jpg', 'other', 'vegetable'),
      ('Fennel', 'Green', 31, 0, 'Anise-like flavor', 'fennel.jpg', 'spicy', 'vegetable'),
      ('Fig', 'Purple', 74, 0, 'Sweet and chewy', 'fig.jpg', 'sweet', 'fruit'),
      ('Garlic', 'White', 5, 0, 'Pungent and savory', 'garlic.jpg', 'fresh', 'vegetable'),
      ('Gin', 'Clear', 96, 40, 'Botanical and juniper', 'gin.jpg', 'herbaceous', 'alcohol'),
      ('Ginger', 'Brown', 80, 0, 'Spicy and warming', 'ginger.jpg', 'spicy', 'spice'),
      ('Ginseng', 'Brown', 5, 0, 'Earthy and bitter', 'ginseng.jpg', 'other', 'herb'),
      ('Goji Berry', 'Red', 50, 0, 'Sweet and tangy', 'gojiberry.jpg', 'sweet', 'fruit'),
      ('Grape', 'Purple', 69, 0, 'Sweet and juicy', 'grape.jpg', 'fruity', 'fruit'),
      ('Green Bean', 'Green', 31, 0, 'Crisp and fresh', 'greenbean.jpg', 'other', 'vegetable'),
      ('Green Tea', 'Green', 2, 0, 'Grassy and soothing', 'greentea.jpg', 'other', 'herb'),
      ('Guava', 'Pink', 68, 0, 'Sweet and tropical', 'guava.jpg', 'fruity', 'fruit'),
      ('Hazelnut', 'Brown', 628, 0, 'Nutty and rich', 'hazelnut.jpg', 'other', 'fruit'),
      ('Honey', 'Yellow', 304, 0, 'Sweet and golden', 'honey.jpg', 'sweet', 'other'),
      ('Hops', 'Green', 0, 0, 'Bitter and floral', 'hops.jpg', 'bitter', 'herb'),
      ('Jalapeño', 'Green', 29, 0, 'Spicy and tangy', 'jalapeno.jpg', 'spicy', 'vegetable'),       
      ('Jasmine', 'White', 2, 0, 'Floral and fragrant', 'jasmine.jpg', 'floral', 'herb'),
      ('Kale', 'Green', 33, 0, 'Nutrient-dense and earthy', 'kale.jpg', 'herbaceous', 'vegetable'),
      ('Kiwi', 'Green', 61, 0, 'Tangy and tropical', 'kiwi.jpg', 'fruity', 'fruit'),
      ('Lavender', 'Purple', 4, 0, 'Floral and aromatic', 'lavender.jpg', 'floral', 'herb'),
      ('Leek', 'White', 61, 0, 'Mild and oniony', 'leek.jpg', 'other', 'vegetable'),
      ('Lemon', 'Yellow', 20, 0, 'Citrus flavor', 'lemon.jpg', 'sour', 'fruit'),
      ('Lemongrass', 'Green', 99, 0, 'Citrusy and lemony', 'lemongrass.jpg', 'other', 'herb'),
      ('Lime', 'Green', 30, 0, 'Tart and zesty', 'lime.jpg', 'sour', 'fruit'),
      ('Lychee', 'Pink', 66, 0, 'Sweet and floral', 'lychee.jpg', 'floral', 'fruit'),
      ('Mango', 'Orange', 60, 0, 'Sweet and tropical', 'mango.jpg', 'fruity', 'fruit'),
      ('Maple Syrup', 'Brown', 260, 0, 'Sweet and rich', 'maplesyrup.jpg', 'sweet', 'syrup'),
      ('Marjoram', 'Green', 3, 0, 'Sweet and citrusy', 'marjoram.jpg', 'sweet', 'herb'),
      ('Melon', 'Various', 34, 0, 'Sweet and refreshing', 'melon.jpg', 'sweet', 'fruit'),
      ('Mint', 'Green', 5, 0, 'Cool and refreshing', 'mint.jpg', 'fresh', 'herb'),
      ('Mushroom', 'Various', 22, 0, 'Umami and earthy', 'mushroom.jpg', 'earthy', 'vegetable'),
      ('Nutmeg', 'Brown', 525, 0, 'Warm and spicy', 'nutmeg.jpg', 'spicy', 'spice'),
      ('Olive', 'Green', 115, 0, 'Savory and briny', 'olive.jpg', 'salty', 'fruit'),
      ('Onion', 'White', 40, 0, 'Pungent and sweet', 'onion.jpg', 'sour', 'vegetable'),
      ('Orange', 'Orange', 47, 0, 'Citrusy and vibrant', 'orange.jpg', 'fruity', 'fruit'),
      ('Oregano', 'Green', 2, 0, 'Robust and peppery', 'oregano.jpg', 'fresh', 'herb'),
      ('Papaya', 'Orange', 43, 0, 'Sweet and tropical', 'papaya.jpg', 'fruity', 'fruit'),
      ('Paprika', 'Red', 19, 0, 'Smoky and sweet', 'paprika.jpg', 'other', 'spice'),
      ('Parsley', 'Green', 2, 0, 'Fresh and earthy', 'parsley.jpg', 'fresh', 'herb'),
      ('Peach', 'Orange', 39, 0, 'Sweet and velvety', 'peach.jpg', 'fruity', 'fruit'),
      ('Peanut', 'Brown', 567, 0, 'Nutty and crunchy', 'peanut.jpg', 'other', 'fruit'),
      ('Pear', 'Yellow', 57, 0, 'Sweet and juicy', 'pear.jpg', 'fruity', 'fruit'),
      ('Peppermint', 'Green', 70, 0, 'Cool and minty', 'peppermint.jpg', 'peppery', 'herb'),
      ('Persimmon', 'Orange', 81, 0, 'Sweet and honey-like', 'persimmon.jpg', 'sweet', 'fruit'),
      ('Pineapple', 'Yellow', 50, 0, 'Sweet and tropical', 'pineapple.jpg', 'fruity', 'fruit'),
      ('Pistachio', 'Green', 562, 0, 'Nutty and slightly sweet', 'pistachio.jpg', 'sweet', 'fruit'),
      ('Plum', 'Purple', 46, 0, 'Sweet and tart', 'plum.jpg', 'fruity', 'fruit'),
      ('Pomegranate', 'Red', 83, 0, 'Sweet and tangy', 'pomegranate.jpg', 'other', 'fruit'),
      ('Popcorn', 'Yellow', 30, 0, 'Buttery and salty', 'popcorn.jpg', 'other', 'other'),
      ('Pork', 'Pink', 242, 0, 'Rich and savory', 'pork.jpg', 'other', 'meat'),
      ('Potato', 'Brown', 130, 0, 'Starchy and versatile', 'potato.jpg', 'other', 'vegetable'),
      ('Pumpkin', 'Orange', 26, 0, 'Sweet and earthy', 'pumpkin.jpg', 'other', 'vegetable'),
      ('Red Wine', 'Red', 125, 12, 'Bold and full-bodied', 'redwine.jpg', 'other', 'alcohol'),
      ('Rosé', 'Pink', 100, 12, 'Light and refreshing', 'rose.jpg', 'other', 'alcohol'),
      ('Rum', 'Brown', 231, 40, 'Sweet and molasses', 'rum.jpg', 'sweet', 'alcohol'),
      ('Salmon', 'Pink', 206, 0, 'Rich and flaky', 'salmon.jpg', 'other', 'seafood'),
      ('Salt', 'White', 0, 0, 'Essential seasoning', 'salt.jpg', 'salty', 'condiment'),
      ('Scallion', 'Green', 32, 0, 'Mild onion flavor', 'scallion.jpg', 'sour', 'vegetable'),
      ('Sesame Seed', 'White', 573, 0, 'Nutty and crunchy', 'sesameseed.jpg', 'earthy', 'herb'),
      ('Shallot', 'Purple', 72, 0, 'Sweet and mild', 'shallot.jpg', 'sweet', 'vegetable'),
      ('Shrimp', 'Pink', 85, 0, 'Sweet and briny', 'shrimp.jpg', 'other', 'seafood'),
      ('Snow Pea', 'Green', 42, 0, 'Sweet and crisp', 'snowpea.jpg', 'other', 'vegetable'),
      ('Soy Sauce', 'Brown', 8, 0, 'Savory and salty', 'soysauce.jpg', 'salty', 'sauce'),
      ('Spinach', 'Green', 23, 0, 'Leafy and earthy', 'spinach.jpg', 'other', 'vegetable'),
      ('Strawberry', 'Red', 32, 0, 'Sweet and juicy', 'strawberry.jpg', 'fruity', 'fruit'),
      ('Sweet Potato', 'Orange', 86, 0, 'Sweet and starchy', 'sweetpotato.jpg', 'other', 'vegetable'),
      ('Tequila', 'Clear', 96, 40, 'Agave spirit', 'tequila.jpg', 'spicy', 'alcohol'),
      ('Tarragon', 'Green', 295, 0, 'Herbaceous and bittersweet', 'tarragon.jpg', 'fresh', 'herb'),
      ('Thyme', 'Green', 2, 0, 'Earthy and lemony', 'thyme.jpg', 'fresh', 'herb'),
      ('Tomato', 'Red', 18, 0, 'Juicy and acidic', 'tomato.jpg', 'sour', 'vegetable'),
      ('Tuna', 'Pink', 144, 0, 'Meaty and flavorful', 'tuna.jpg', 'umami', 'seafood'),
      ('Turmeric', 'Yellow', 354, 0, 'Warm and earthy', 'turmeric.jpg', 'other', 'spice'),
      ('Turnip', 'Purple', 28, 0, 'Peppery and sweet', 'turnip.jpg', 'other', 'vegetable'),
      ('Vanilla', 'Brown', 288, 0, 'Sweet and aromatic', 'vanilla.jpg', 'sweet', 'herb'),
      ('Vodka', 'Clear', 96, 40, 'Neutral and smooth', 'vodka.jpg', 'neutral', 'alcohol'),
      ('Walnut', 'Brown', 654, 0, 'Nutty and rich', 'walnut.jpg', 'other', 'fruit'),
      ('Wasabi', 'Green', 19, 0, 'Pungent and spicy', 'wasabi.jpg', 'spicy', 'condiment'),
      ('Watermelon', 'Red', 30, 0, 'Sweet and refreshing', 'watermelon.jpg', 'neutral', 'fruit'),
      ('Wheat Germ', 'Brown', 382, 0, 'Nutty and nutritious', 'wheatgerm.jpg', 'other', 'herb'),
      ('Whisky', 'Various', 250, 40, 'Rich and smoky', 'whisky.jpg', 'other', 'alcohol'),
      ('White Wine', 'White', 120, 12, 'Crisp and fruity', 'whitewine.jpg', 'fruity', 'alcohol'),
      ('Yogurt', 'White', 59, 0, 'Creamy and tangy', 'yogurt.jpg', 'other', 'cream'),
      ('Zucchini', 'Green', 17, 0, 'Mild and versatile', 'zucchini.jpg', 'neutral', 'vegetable'),
      ('Orange Juice', 'Orange', 45, 0, 'Freshly squeezed and citrusy', 'orangejuice.jpg', 'fruity', 'softdrink'),
      ('Schweppes', 'Various', 38, 0, 'Bubbly and refreshing', 'schweppes.jpg', 'neutral', 'softdrink'),
      ('Coca-Cola', 'Brown', 140, 0, 'Sweet and carbonated', 'cocacola.jpg', 'sweet', 'softdrink'),
      ('Multifruit Juice', 'Various', 60, 0, 'Blend of various fruits', 'multifruit.jpg', 'fruity', 'softdrink'),
      ('Sprite', 'Clear', 95, 0, 'Lemon-lime and bubbly', 'sprite.jpg', 'fruity', 'softdrink'),
      ('Fanta', 'Orange', 160, 0, 'Orange-flavored and fizzy', 'fanta.jpg', 'fruity', 'softdrink'),
      ('Pepsi', 'Brown', 150, 0, 'Sweet and cola-flavored', 'pepsi.jpg', 'sweet', 'softdrink'),
      ('Ginger Ale', 'Clear', 90, 0, 'Ginger-flavored and sparkling', 'gingerale.jpg', 'spicy', 'softdrink'),
      ('Lemonade', 'Yellow', 80, 0, 'Tart and refreshing', 'lemonade.jpg', 'sour', 'softdrink'),
      ('Iced Tea', 'Brown', 30, 0, 'Cool and tea-infused', 'icedtea.jpg', 'other', 'softdrink'),
      ('Club Soda', 'Clear', 0, 0, 'Carbonated and plain', 'clubsoda.jpg', 'neutral', 'softdrink'),
      ('Cranberry Juice', 'Red', 46, 0, 'Tart and tangy', 'cranberryjuice.jpg', 'acidulous', 'softdrink'),
      ('Apple Juice', 'Gold', 114, 0, 'Sweet and fruity', 'applejuice.jpg', 'fruity', 'softdrink'),
      ('Grapefruit Soda', 'Pink', 120, 0, 'Citrusy and effervescent', 'grapefruitsoda.jpg', 'fruity', 'softdrink'),
      ('Pineapple Juice', 'Yellow', 60, 0, 'Tropical and sweet', 'pineapplejuice.jpg', 'fruity', 'softdrink'),
      ('Blackcurrant Cordial', 'Purple', 50, 0, 'Rich and berry-flavored', 'blackcurrantcordial.jpg', 'fruity', 'softdrink'),
      ('Lime Cordial', 'Green', 40, 0, 'Tart and zesty', 'limecordial.jpg', 'sour', 'softdrink'),
      ('Cherry Cola', 'Red', 170, 0, 'Sweet and cherry-infused', 'cherrycola.jpg', 'fruity', 'softdrink'),
      ('Blue Raspberry Lemonade', 'Blue', 90, 0, 'Fruity and vibrant', 'blueraspberrylemonade.jpg', 'fruity', 'softdrink'),
      ('Mango Passionfruit Cooler', 'Orange', 120, 0, 'Tropical and exotic', 'mangopassionfruitcooler.jpg', 'fruity', 'softdrink'),
      ('Peach Iced Tea', 'Orange', 45, 0, 'Sweet and peach-flavored', 'peachicedtea.jpg', 'fruity', 'softdrink'),
      ('Strawberry Kiwi Splash', 'Red', 70, 0, 'Berry and tropical fusion', 'strawberrykiwisplash.jpg', 'fruity', 'softdrink'),
      ('Grape Juice', 'Purple', 60, 0, 'Sweet and grape-flavored', 'grapejuice.jpg', 'fruity', 'softdrink'),
      ('Limeade', 'Green', 65, 0, 'Tart and lime-infused', 'limeade.jpg', 'sour', 'softdrink'),
      ('Mango Nectar', 'Orange', 120, 0, 'Thick and mango-flavored', 'mangonectar.jpg', 'fruity', 'softdrink'),
      ('Raspberry Lemon Sparkler', 'Red', 80, 0, 'Raspberry and lemon combination', 'raspberrylemonsparkler.jpg', 'fruity', 'softdrink'),
      ('Lemon Lime Bitters', 'Yellow', 120, 0, 'Citrusy with a hint of bitterness', 'lemonlimebitters.jpg', 'fruity', 'softdrink'),
      ('Passionfruit Soda', 'Orange', 95, 0, 'Passionfruit-flavored and effervescent', 'passionfruitsoda.jpg', 'fruity', 'softdrink'),
      ('Hibiscus Cooler', 'Pink', 70, 0, 'Floral and refreshing', 'hibiscuscooler.jpg', 'floral', 'softdrink'),
      ('Pomegranate Lemonade', 'Red', 85, 0, 'Pomegranate-infused and tart', 'pomegranatelemonade.jpg', 'acidulous', 'softdrink'),
      ('Blueberry Sparkle', 'Blue', 60, 0, 'Sweet and blueberry-infused', 'blueberrysparkle.jpg', 'fruity', 'softdrink'),
      ('Passionfruit Iced Tea', 'Orange', 40, 0, 'Passionfruit-flavored and refreshing', 'passionfruiticedtea.jpg', 'fruity', 'softdrink'),
      ('Kiwi Lemonade', 'Green', 75, 0, 'Tart and kiwi-infused', 'kiwilemonade.jpg', 'sour', 'softdrink'),
      ('Peach Mango Fizz', 'Orange', 110, 0, 'Peach and mango combination', 'peachmangofizz.jpg', 'fruity', 'softdrink'),
      ('Strawberry Pineapple Splash', 'Red', 90, 0, 'Strawberry and pineapple fusion', 'strawberrypineapplesplash.jpg', 'fruity', 'softdrink'),
      ('Coconut Water', 'Clear', 45, 0, 'Natural and hydrating', 'coconutwater.jpg', 'neutral', 'softdrink'),
      ('Raspberry Fizz', 'Red', 80, 0, 'Raspberry-flavored and fizzy', 'raspberryfizz.jpg', 'fruity', 'softdrink'),
      ('Lime Mint Cooler', 'Green', 65, 0, 'Refreshing lime and mint infusion', 'limemintcooler.jpg', 'fruity', 'softdrink'),
      ('Blackberry Lemonade', 'Purple', 75, 0, 'Sweet and tart blackberry with lemon', 'blackberrylemonade.jpg', 'fruity', 'softdrink'),
      ('Orange Creamsicle', 'Orange', 120, 0, 'Citrusy orange with creamy vanilla', 'orangecreamsicle.jpg', 'fruity', 'softdrink'),
      ('Pineapple Coconut Splash', 'Yellow', 90, 0, 'Tropical pineapple with creamy coconut', 'pineapplecoconutsplash.jpg', 'fruity', 'softdrink'),
      ('Strawberry Banana Smoothie', 'Pink', 150, 0, 'Smooth blend of strawberry and banana', 'strawberrybananasmoothie.jpg', 'fruity', 'softdrink'),
      ('Mint Lemon Iced Tea', 'Green', 30, 0, 'Iced tea with a hint of mint and lemon', 'mintlemonicedtea.jpg', 'fruity', 'softdrink'),
      ('Blueberry Mint Sparkler', 'Blue', 70, 0, 'Blueberry-infused sparkler with a touch of mint', 'blueberrymintsparkler.jpg', 'fruity', 'softdrink'),
      ('Peach Raspberry Refresher', 'Orange', 85, 0, 'Peach and raspberry combination', 'peachraspberryrefresher.jpg', 'fruity', 'softdrink'),
      ('Cucumber Mint Splash', 'Green', 25, 0, 'Cool cucumber with a hint of refreshing mint', 'cucumbermintsplash.jpg', 'fruity', 'softdrink'),
      ('Vanilla Syrup', 'Brown', 200, 0, 'Sweet and aromatic vanilla flavor', 'vanillasyrup.jpg', 'sweet', 'syrup'),
      ('Caramel Syrup', 'Brown', 180, 0, 'Rich and buttery caramel infusion', 'caramelsyrup.jpg', 'sweet', 'syrup'),
      ('Hazelnut Syrup', 'Brown', 210, 0, 'Nutty and flavorful hazelnut essence', 'hazelnutsyrup.jpg', 'fruity', 'syrup'),
      ('Raspberry Syrup', 'Red', 160, 0, 'Sweet and tangy raspberry infusion', 'raspberrysyrup.jpg', 'fruity', 'syrup'),
      ('Strawberry Syrup', 'Red', 140, 0, 'Sweet and vibrant strawberry flavor', 'strawberrysyrup.jpg', 'fruity', 'syrup'),
      ('Blueberry Syrup', 'Blue', 150, 0, 'Rich and fruity blueberry essence', 'blueberrysyrup.jpg', 'fruity', 'syrup'),
      ('Peach Syrup', 'Orange', 170, 0, 'Sweet and juicy peach infusion', 'peachsyrup.jpg', 'fruity', 'syrup'),
      ('Coconut Syrup', 'White', 180, 0, 'Sweet and tropical coconut flavor', 'coconutsyrup.jpg', 'fruity', 'syrup'),
      ('Mint Syrup', 'Green', 120, 0, 'Cool and refreshing mint infusion', 'mintsyrup.jpg', 'fruity', 'syrup'),
      ('Lemon Syrup', 'Yellow', 130, 0, 'Citrusy and zesty lemon essence', 'lemonsyrup.jpg', 'fruity', 'syrup'),
      ('Orange Syrup', 'Orange', 140, 0, 'Sweet and citrusy orange flavor', 'orangesyrup.jpg', 'fruity', 'syrup'),
      ('Cherry Syrup', 'Red', 160, 0, 'Sweet and tart cherry infusion', 'cherrysyrup.jpg', 'fruity', 'syrup'),
      ('Pineapple Syrup', 'Yellow', 150, 0, 'Tropical and sweet pineapple essence', 'pineapplesyrup.jpg', 'fruity', 'syrup'),
      ('Gingerbread Syrup', 'Brown', 190, 0, 'Warm and spicy gingerbread flavor', 'gingerbreadsyrup.jpg', 'spicy', 'syrup'),
      ('Maple Syrup', 'Brown', 220, 0, 'Rich and sweet maple essence', 'maplesyrup.jpg', 'sweet', 'syrup'),
      ('Ice', 'Clear', 0, 0, 'Frozen water', 'ice.jpg', 'neutral', 'other');
    `.execute(trx);
  });
}

export async function down(db: Kysely<Database>): Promise<void> {
  await db.transaction().execute(async (trx) => {
    await sql`
      TRUNCATE ingredient;
    `.execute(trx);
  });
}
