import { sql } from 'kysely';

import { db } from '@app/backend-shared';

await db.transaction().execute(async (trx) => {
  await sql`
    INSERT INTO consumer (email, password, firstname, lastname, birthdate, gender, country, created_at)
    VALUES
    ('email1@example.com', 'password1', 'John', 'Doe', '1990-01-01', 'Male', 'USA', NOW()),
    ('email2@example.com', 'password2', 'Jane', 'Smith', '1985-05-15', 'Female', 'Canada', NOW()),
    ('email3@example.com', 'password3', 'Alice', 'Johnson', '1988-09-20', 'Female', 'Australia', NOW()),
    ('email4@example.com', 'password4', 'Mark', 'Williams', '1992-11-30', 'Male', 'UK', NOW()),
    ('email5@example.com', 'password5', 'Samantha', 'Brown', '1987-07-12', 'Female', 'Germany', NOW()),
    ('email6@example.com', 'password6', 'Ryan', 'Taylor', '1994-04-05', 'Male', 'France', NOW()),
    ('email7@example.com', 'password7', 'Emily', 'Clark', '1989-08-25', 'Female', 'Japan', NOW()),
    ('email8@example.com', 'password8', 'David', 'Lee', '1991-02-18', 'Male', 'Brazil', NOW()),
    ('email9@example.com', 'password9', 'Olivia', 'White', '1986-06-22', 'Female', 'India', NOW()),
    ('email10@example.com', 'password10', 'Michael', 'Anderson', '1993-12-15', 'Male', 'China', NOW()),
    ('email11@example.com', 'password11', 'Emma', 'Johnson', '1984-03-08', 'Female', 'South Africa', NOW()),
    ('email12@example.com', 'password12', 'Daniel', 'Smith', '1996-09-10', 'Male', 'Mexico', NOW()),
    ('email13@example.com', 'password13', 'Sophia', 'Davis', '1983-11-24', 'Female', 'Italy', NOW()),
    ('email14@example.com', 'password14', 'Christopher', 'Martinez', '1997-07-03', 'Male', 'Spain', NOW()),
    ('email15@example.com', 'password15', 'Ava', 'Brown', '1982-04-17', 'Female', 'Russia', NOW()),
    ('email16@example.com', 'password16', 'Matthew', 'Taylor', '1998-01-20', 'Male', 'South Korea', NOW()),
    ('email17@example.com', 'password17', 'Isabella', 'Miller', '1981-05-14', 'Female', 'Netherlands', NOW()),
    ('email18@example.com', 'password18', 'Andrew', 'Wilson', '1999-06-28', 'Male', 'Argentina', NOW()),
    ('email19@example.com', 'password19', 'Grace', 'Moore', '1980-09-05', 'Female', 'New Zealand', NOW()),
    ('email20@example.com', 'password20', 'Ethan', 'Harris', '2000-02-12', 'Male', 'Sweden', NOW()),
    ('email21@example.com', 'password21', 'Chloe', 'Perez', '1979-08-08', 'Female', 'Norway', NOW()),
    ('email22@example.com', 'password22', 'Jacob', 'Gonzalez', '2001-10-25', 'Male', 'Switzerland', NOW()),
    ('email23@example.com', 'password23', 'Lily', 'Rodriguez', '1978-03-18', 'Female', 'Ireland', NOW()),
    ('email24@example.com', 'password24', 'Logan', 'Lopez', '2002-05-30', 'Male', 'Singapore', NOW()),
    ('email25@example.com', 'password25', 'Madison', 'Jackson', '1977-07-01', 'Female', 'Chile', NOW()),
    ('email26@example.com', 'password26', 'Aiden', 'Turner', '2003-12-10', 'Male', 'Portugal', NOW()),
    ('email27@example.com', 'password27', 'Zoe', 'Martin', '1976-11-22', 'Female', 'Turkey', NOW()),
    ('email28@example.com', 'password28', 'Caleb', 'Hill', '2004-04-05', 'Male', 'Thailand', NOW()),
    ('email29@example.com', 'password29', 'Avery', 'Young', '1975-09-15', 'Female', 'Israel', NOW()),
    ('email30@example.com', 'password30', 'Wyatt', 'Allen', '2005-01-28', 'Male', 'Poland', NOW()),
    ('email31@example.com', 'password31', 'Addison', 'Ward', '1974-02-08', 'Female', 'Greece', NOW()),
    ('email32@example.com', 'password32', 'Gabriel', 'Turner', '2006-06-12', 'Male', 'Czech Republic', NOW()),
    ('email33@example.com', 'password33', 'Natalie', 'Baker', '1973-04-22', 'Female', 'Egypt', NOW()),
    ('email34@example.com', 'password34', 'Jackson', 'Cooper', '2007-09-30', 'Male', 'Kenya', NOW()),
    ('email35@example.com', 'password35', 'Hannah', 'Garcia', '1972-11-05', 'Female', 'Nigeria', NOW()),
    ('email36@example.com', 'password36', 'Owen', 'Fisher', '2008-03-18', 'Male', 'Peru', NOW()),
    ('email37@example.com', 'password37', 'Brooklyn', 'Roberts', '1971-07-01', 'Female', 'Saudi Arabia', NOW()),
    ('email38@example.com', 'password38', 'Liam', 'Hernandez', '2009-12-10', 'Male', 'South Africa', NOW()),
    ('email39@example.com', 'password39', 'Aria', 'Green', '1970-02-22', 'Female', 'United Arab Emirates', NOW()),
    ('email40@example.com', 'password40', 'Mason', 'Taylor', '2010-06-28', 'Male', 'Indonesia', NOW()),
    ('email41@example.com', 'password41', 'Ella', 'Adams', '1969-04-05', 'Female', 'Malaysia', NOW()),
    ('email42@example.com', 'password42', 'Noah', 'Scott', '2011-09-15', 'Male', 'Philippines', NOW()),
    ('email43@example.com', 'password43', 'Scarlett', 'Perez', '1968-11-28', 'Female', 'Vietnam', NOW()),
    ('email44@example.com', 'password44', 'Lucas', 'Campbell', '2012-01-30', 'Male', 'South Africa', NOW()),
    ('email45@example.com', 'password45', 'Aubrey', 'Russell', '1967-03-08', 'Female', 'Sweden', NOW()),
    ('email46@example.com', 'password46', 'Elijah', 'Ward', '2013-07-12', 'Male', 'Brazil', NOW()),
    ('email47@example.com', 'password47', 'Leah', 'Hill', '1966-09-20', 'Female', 'Argentina', NOW()),
    ('email48@example.com', 'password48', 'Aiden', 'Sanders', '2014-02-12', 'Male', 'Spain', NOW()),
    ('email49@example.com', 'password49', 'Grace', 'Turner', '1965-04-17', 'Female', 'Italy', NOW()),
    ('email50@example.com', 'password50', 'Benjamin', 'Carter', '2015-08-25', 'Male', 'France', NOW());
  `.execute(trx);

  await sql`
    INSERT INTO command (totalAmount, totalQuantity, consumer_id, status, created_at)
    VALUES
    (50, 3, 1, 'completed', NOW()),
    (150, 7, 2, 'completed', NOW()),
    (10, 13, 3, 'completed', NOW()),
    (30, 7, 4, 'completed', NOW()),
    (200, 10, 5, 'completed', NOW()),
    (10, 2, 6, 'completed', NOW()),
    (40, 4, 7, 'completed', NOW()),
    (700, 20, 8, 'completed', NOW()),
    (50, 3, 9, 'completed', NOW()),
    (60, 5, 10, 'completed', NOW()),
    (100, 10, 11, 'completed', NOW()),
    (100, 5, 12, 'completed', NOW()),
    (200, 5, 13, 'completed', NOW()),
    (50, 7, 14, 'completed', NOW()),
    (80, 8, 15, 'completed', NOW()),
    (90, 5, 16, 'completed', NOW()),
    (30, 14, 17, 'completed', NOW()),
    (250, 6, 18, 'completed', NOW()),
    (150, 3, 19, 'completed', NOW()),
    (80, 7, 20, 'completed', NOW()),
    (120, 12, 21, 'completed', NOW()),
    (40, 1, 22, 'completed', NOW()),
    (180, 11, 23, 'completed', NOW()),
    (75, 9, 24, 'completed', NOW()),
    (200, 8, 25, 'completed', NOW()),
    (100, 11, 26, 'completed', NOW()),
    (20, 13, 27, 'completed', NOW()),
    (50, 5, 28, 'completed', NOW()),
    (90, 4, 29, 'completed', NOW()),
    (120, 3, 30, 'completed', NOW()),
    (160, 6, 31, 'completed', NOW()),
    (110, 1, 32, 'completed', NOW()),
    (70, 8, 33, 'completed', NOW()),
    (200, 15, 34, 'completed', NOW()),
    (30, 2, 35, 'completed', NOW()),
    (80, 1, 36, 'completed', NOW()),
    (150, 14, 37, 'completed', NOW()),
    (40, 3, 38, 'completed', NOW()),
    (95, 10, 39, 'completed', NOW()),
    (200, 11, 40, 'completed', NOW()),
    (170, 1, 41, 'completed', NOW()),
    (130, 9, 42, 'completed', NOW()),
    (50, 6, 43, 'completed', NOW()),
    (20, 4, 44, 'completed', NOW()),
    (65, 1, 45, 'completed', NOW()),
    (110, 12, 46, 'completed', NOW()),
    (180, 5, 47, 'completed', NOW()),
    (90, 6, 48, 'completed', NOW()),
    (120, 11, 49, 'completed', NOW()),
    (40, 2, 50, 'completed', NOW());
  `.execute(trx);

  await sql`
    INSERT INTO product (name, brand, category, image)
    VALUES
      ('Crème de Jour Re-Fortifiante FPS 20', 'Age Perfect Golden Age', 'soin peau', 'creme-de-jour-re-fortifiante-fps-20.jpg'),
      ('Lotion Tonique Hydratante', 'Hydra Genius', 'soin peau', 'lotion-tonique-hydratante.jpg'),
      ('Sérum Anti-Âge Régénérant', 'Revitalift Laser X3', 'soin peau', 'serum-anti-age-regenerant.jpg'),
      ('Gel Douche Rafraîchissant', 'Men Expert Hydra Energetic', 'hygiène corporelle', 'gel-douche-rafraichissant.jpg'),
      ('Lait Démaquillant Apaisant', 'Sublime Soft', 'soin peau', 'lait-demaquillant-apaisant.jpg'),
      ('Déodorant Invisible 48H', 'Invisible Protect', 'hygiène corporelle', 'deodorant-invisible-48h.jpg'),
      ('Baume à Lèvres Réparateur', 'Lip Expertise', 'soin lèvres', 'baume-a-lèvres-reparateur.jpg'),
      ('Eau Micellaire Nettoyante', 'Skin Active', 'soin peau', 'eau-micellaire-nettoyante.jpg'),
      ('Dentifrice Blanchissant', 'White Perfect', 'hygiène bucco-dentaire', 'dentifrice-blanchissant.jpg'),
      ('Savon Liquide Hydratant', 'Nutra-Glow', 'hygiène corporelle', 'savon-liquide-hydratant.jpg'),
      ('Lotion Après-Rasage', 'Men Expert Hydra Sensitive', 'soin peau', 'lotion-apres-rasage.jpg'),
      ('Crayon à Sourcils Précision', 'Brow Artist', 'soin yeux', 'crayon-a-sourcils-precision.jpg'),
      ('Baume à Barbe Nourrissant', 'BarberClub', 'soin barbe', 'baume-a-barbe-nourrissant.jpg'),
      ('Lingettes Démaquillantes', 'Micellar Water', 'soin peau', 'lingettes-demaquillantes.jpg'),
      ('Démaquillant Yeux Waterproof', 'Bi-Facil', 'soin peau', 'demquillant-yeux-waterproof.jpg'),
      ('Crème Hydratante Visage et Corps', 'Nutra-Glow', 'soin peau', 'creme-hydratante-visage-et-corps.jpg'),
      ('Mousse Nettoyante Purifiante', 'Pure-Clay', 'soin peau', 'mousse-nettoyante-purifiante.jpg'),
      ('Crayon à Sourcils Brow Artist Xpert', 'Brow Artist', 'soin yeux', 'crayon-a-sourcils-brow-artist-xpert.jpg'),
      ('Eau Micellaire Bi-Phase Waterproof', 'Micellar Water', 'soin peau', 'eau-micellaire-bi-phase-waterproof.jpg'),
      ('Gel Douche Énergisant', 'Men Expert Hydra Energetic', 'hygiène corporelle', 'gel-douche-energisant.jpg'),
      ('Crème Mains Réparatrice', 'Age Perfect Golden Age', 'soin mains', 'creme-mains-reparatrice.jpg'),
      ('Lait Hydratant Corps', 'Hydra Genius', 'soin corps', 'lait-hydratant-corps.jpg'),
      ('Huile Nourrissante pour le Corps', 'Nutra-Glow', 'soin corps', 'huile-nourrissante-corps.jpg'),
      ('Gommage Corps Revitalisant', 'Body Expertise', 'soin corps', 'gommage-corps-revitalisant.jpg'),
      ('Beurre Corporel Apaisant', 'Sublime Soft', 'soin corps', 'beurre-corporel-apaisant.jpg'),
      ('Gel Douche Hydratant', 'Nutra-Glow', 'hygiène corporelle', 'gel-douche-hydratant.jpg'),
      ('Crème Nourrissante pour les Pieds', 'Foot Expertise', 'soin pieds', 'creme-nourrissante-pieds.jpg'),
      ('Sérum Hydratant pour le Corps', 'Hydra Genius', 'soin corps', 'serum-hydratant-corps.jpg'),
      ('Crème Exfoliante pour le Corps', 'Body Expertise', 'soin corps', 'creme-exfoliante-corps.jpg'),
      ('Déodorant Spray Fraîcheur', 'Sublime Soft', 'hygiène corporelle', 'deodorant-spray-fraicheur.jpg'),
      ('Baume Réparateur pour les Mains', 'Nutra-Glow', 'soin mains', 'baume-reparateur-mains.jpg'),
      ('Crème Raffermissante pour le Buste', 'Body Expertise', 'soin corps', 'creme-raffermissante-buste.jpg'),
      ('Gel Lavant Intime', 'Intimate Expertise', 'hygiène intime', 'gel-lavant-intime.jpg'),
      ('Gel Douche Exfoliant', 'Nutra-Glow', 'soin corps', 'gel-douche-exfoliant-corps.jpg'),
      ('Baume Hydratant pour les Pieds', 'Foot Expertise', 'soin pieds', 'baume-hydratant-pieds.jpg'),
      ('Spray Hydratant Corps', 'Hydra Genius', 'soin corps', 'spray-hydratant-corps.jpg'),
      ('Lotion Apaisante Après-Soleil', 'Sublime Soft', 'soin peau', 'lotion-apaisante-apres-soleil.jpg'),
      ('Crème Hydratante Corps', 'Hydra Genius', 'soin corps', 'creme-hydratante-corps.jpg'),
      ('Gommage Corps Revitalisant', 'Body Expertise', 'soin corps', 'gommage-corps-revitalisant.jpg'),
      ('Huile Nourrissante pour le Corps', 'NutraCare', 'soin corps', 'huile-nourrissante-corps.jpg'),
      ('Beurre Corporel Apaisant', 'Calm Essence', 'soin corps', 'beurre-corporel-apaisant.jpg'),
      ('Gel Douche Hydratant Corps', 'Hydra Spa', 'soin corps', 'gel-douche-hydratant-corps.jpg'),
      ('Lotion Tonique Rafraîchissante pour le Corps', 'Cool Mist', 'soin corps', 'lotion-tonique-rafraichissante-corps.jpg'),
      ('Baume Réparateur pour Pieds Secs', 'Foot Comfort', 'soin corps', 'baume-reparateur-pieds-secs.jpg'),
      ('Sérum Raffermissant Buste et Décolleté', 'Firm Lift', 'soin corps', 'serum-raffermissant-buste-decollete.jpg'),
      ('Crème Anti-Vergetures', 'Stretch Care', 'soin corps', 'creme-anti-vergetures.jpg'),
      ('Spray Hydratant Corps Express', 'Quick Moisture', 'soin corps', 'spray-hydratant-corps-express.jpg'),
      ('Huile Nourrissante Corps', 'Nutra-Glow', 'soin corps', 'huile-nourrissante-corps.jpg'),
      ('Crème Exfoliante Corps', 'Hydra Genius', 'soin corps', 'creme-exfoliante-corps.jpg'),
      ('Gel Hydratant Après-Soleil', 'Sublime Soft', 'soin corps', 'gel-hydratant-apres-soleil.jpg'),
      ('Baume Hydratant Intense', 'Age Perfect Golden Age', 'soin corps', 'baume-hydratant-intense.jpg'),
      ('Lait Tonique Hydratant', 'Hydra Genius', 'soin corps', 'lait-tonique-hydratant.jpg'),
      ('Sérum Hydratant Corps', 'Skin Active', 'soin corps', 'serum-hydratant-corps.jpg'),
      ('Gommage Corps Revitalisant', 'Pure-Clay', 'soin corps', 'gommage-corps-revitalisant.jpg'),
      ('Baume Réparateur Pieds', 'Nutra-Glow', 'soin pieds', 'baume-reparateur-pieds.jpg'),
      ('Spray Rafraîchissant Pieds', 'Sublime Soft', 'soin pieds', 'spray-rafraichissant-pieds.jpg'),
      ('gommage point noir', 'Sublime Soft', 'soin visage', 'gommage-point-noir.jpg'),
      ('Crème Anti-Vergetures', 'Age Perfect Golden Age', 'soin corps', 'creme-anti-vergetures.jpg');
  `.execute(trx);

  await sql`
    INSERT INTO command_line (unity_price, quantity, product_id, total_price, command_id)
    VALUES
        (20, 1, 46, 20, 1),
        (40, 2, 1, 80, 1),
        (10, 1, 2, 10, 2),
        (20, 1, 12, 20, 2),
        (5, 3, 35, 15, 2),
        (15, 2, 17, 30, 3),
        (30, 1, 45, 30, 3),
        (8, 4, 2, 32, 3),
        (18, 2, 3, 36, 4),
        (6, 3, 22, 18, 4),
        (25, 1, 56, 25, 5),
        (50, 2, 4, 100, 5),
        (12, 1, 29, 12, 6),
        (25, 1, 5, 25, 6),
        (7, 3, 53, 21, 6),
        (30, 2, 6, 60, 7),
        (60, 1, 7, 60, 7),
        (15, 4, 8, 60, 8),
        (30, 2, 9, 60, 8),
        (10, 3, 10, 30, 8),
        (5, 1, 11, 5, 9),
        (15, 2, 12, 30, 9),
        (8, 1, 13, 8, 9),
        (10, 1, 14, 10, 10),
        (20, 3, 15, 60, 10),
        (10, 2, 16, 20, 11),
        (25, 1, 17, 25, 11),
        (5, 4, 18, 20, 11),
        (15, 2, 19, 30, 12),
        (6, 3, 20, 18, 12),
        (12, 1, 21, 12, 13),
        (30, 1, 22, 30, 13),
        (7, 3, 23, 21, 13),
        (8, 2, 24, 16, 14),
        (16, 1, 25, 16, 14),
        (20, 4, 26, 80, 15),
        (40, 2, 27, 80, 15),
        (10, 3, 28, 30, 15),
        (15, 1, 29, 15, 16),
        (30, 2, 30, 60, 16),
        (5, 1, 31, 5, 17),
        (15, 2, 32, 30, 17),
        (8, 1, 33, 8, 17),
        (10, 1, 34, 10, 18),
        (20, 3, 35, 60, 18),
        (10, 2, 36, 20, 19),
        (25, 1, 37, 25, 19),
        (5, 4, 38, 20, 19),
        (15, 2, 39, 30, 20),
        (6, 3, 40, 18, 20),
        (12, 1, 41, 12, 21),
        (30, 1, 42, 30, 21),
        (7, 3, 43, 21, 21),
        (8, 2, 44, 16, 22),
        (16, 1, 45, 16, 22),
        (20, 4, 46, 80, 23),
        (40, 2, 47, 80, 23),
        (10, 3, 48, 30, 23),
        (15, 1, 49, 15, 24),
        (30, 2, 50, 60, 24),
        (5, 1, 51, 5, 24),
        (15, 2, 52, 30, 24),
        (8, 1, 53, 8, 24),
        (10, 1, 54, 10, 25),
        (20, 3, 55, 60, 25),
        (10, 2, 56, 20, 26),
        (25, 1, 57, 25, 26),
        (5, 4, 1, 20, 26),
        (15, 2, 2, 30, 27),
        (6, 3, 3, 18, 27),
        (12, 1, 4, 12, 28),
        (30, 1, 5, 30, 28),
        (7, 3, 6, 21, 28),
        (8, 2, 7, 16, 29),
        (16, 1, 8, 16, 29),
        (20, 4, 9, 80, 30),
        (40, 2, 10, 80, 30),
        (10, 3, 11, 30, 31),
        (15, 1, 12, 15, 31),
        (30, 2, 13, 60, 32),
        (15, 3, 14, 45, 33),
        (10, 1, 15, 10, 33),
        (5, 2, 16, 10, 34),
        (10, 1, 17, 10, 34),
        (20, 2, 18, 40, 35),
        (40, 1, 19, 40, 35),
        (8, 3, 20, 24, 35),
        (25, 1, 21, 25, 36),
        (50, 2, 22, 100, 36),
        (12, 1, 23, 12, 37),
        (25, 1, 24, 25, 37),
        (7, 3, 25, 21, 37),
        (30, 2, 26, 60, 38),
        (60, 1, 27, 60, 38),
        (15, 4, 28, 60, 39),
        (30, 2, 29, 60, 39),
        (10, 3, 30, 30, 39),
        (15, 2, 31, 30, 40),
        (6, 3, 32, 18, 40),
        (12, 1, 33, 12, 41),
        (30, 1, 34, 30, 41),
        (7, 3, 35, 21, 41),
        (8, 2, 36, 16, 42),
        (16, 1, 37, 16, 42),
        (20, 4, 38, 80, 43),
        (40, 2, 39, 80, 43),
        (10, 3, 40, 30, 43),
        (15, 1, 41, 15, 44),
        (30, 2, 42, 60, 44),
        (6, 3, 43, 18, 45),
        (25, 1, 44, 25, 45),
        (5, 4, 45, 20, 45),
        (15, 2, 46, 30, 46),
        (10, 1, 47, 10, 46),
        (5, 2, 48, 10, 47),
        (10, 1, 49, 10, 47),
        (20, 2, 50, 40, 48),
        (40, 1, 51, 40, 48),
        (8, 3, 52, 24, 48),
        (25, 1, 53, 25, 49),
        (50, 2, 54, 100, 49),
        (12, 1, 55, 12, 50),
        (25, 1, 56, 25, 50),
        (7, 3, 57, 21, 50);
  `.execute(trx);

  await sql`
    INSERT INTO criteria (name)
    VALUES
    ('Couleur de peau'),
    ('Type de peau'),
    ('Problème de peau'),
    ('Sensibilité'),
    ('Routine'),
    ('Exposition au soleil'),
    ('Alimentation'),
    ('Niveau d''activité'),
    ('Tranche d''âge'),
    ('Tabagisme'),
    ('Allergies'),
    ('Traitement'),
    ('Exposition à la pollution'),
    ('Objectif')
  `.execute(trx);
  await sql`
    INSERT INTO criteria_value (criteria_id, value)
    VALUES
      ((SELECT id FROM criteria WHERE name = 'Couleur de peau'), 'Clair'),
      ((SELECT id FROM criteria WHERE name = 'Couleur de peau'), 'Moyen'),
      ((SELECT id FROM criteria WHERE name = 'Couleur de peau'), 'Foncé'),
      ((SELECT id FROM criteria WHERE name = 'Type de peau'), 'Sec'),
      ((SELECT id FROM criteria WHERE name = 'Type de peau'), 'Normal'),
      ((SELECT id FROM criteria WHERE name = 'Type de peau'), 'Gras'),
      ((SELECT id FROM criteria WHERE name = 'Problème de peau'), 'Acné'),
      ((SELECT id FROM criteria WHERE name = 'Problème de peau'), 'Sécheresse'),
      ((SELECT id FROM criteria WHERE name = 'Problème de peau'), 'Rougeurs'),
      ((SELECT id FROM criteria WHERE name = 'Problème de peau'), 'Hyperpigmentation'),
      ((SELECT id FROM criteria WHERE name = 'Problème de peau'), 'Rides'),
      ((SELECT id FROM criteria WHERE name = 'Sensibilité'), 'Non sensible'),
      ((SELECT id FROM criteria WHERE name = 'Sensibilité'), 'Sensible'),
      ((SELECT id FROM criteria WHERE name = 'Sensibilité'), 'Très sensible'),
      ((SELECT id FROM criteria WHERE name = 'Routine'), 'Simple et rapide'),
      ((SELECT id FROM criteria WHERE name = 'Routine'), 'Complète et détaillée'),
      ((SELECT id FROM criteria WHERE name = 'Routine'), 'Minimale'),
      ((SELECT id FROM criteria WHERE name = 'Routine'), 'Matin et soir'),
      ((SELECT id FROM criteria WHERE name = 'Routine'), 'Occasionnelle'),
      ((SELECT id FROM criteria WHERE name = 'Exposition au soleil'), 'Faible'),
      ((SELECT id FROM criteria WHERE name = 'Exposition au soleil'), 'Modérée'),
      ((SELECT id FROM criteria WHERE name = 'Exposition au soleil'), 'Élevée'),
      ((SELECT id FROM criteria WHERE name = 'Exposition au soleil'), 'Très élevée'),
      ((SELECT id FROM criteria WHERE name = 'Exposition au soleil'), 'Variable selon les saisons'),
      ((SELECT id FROM criteria WHERE name = 'Alimentation'), 'Équilibrée'),
      ((SELECT id FROM criteria WHERE name = 'Alimentation'), 'Végétarienne'),
      ((SELECT id FROM criteria WHERE name = 'Alimentation'), 'Riche en fruits et légumes'),
      ((SELECT id FROM criteria WHERE name = 'Alimentation'), 'Riche en protéines'),
      ((SELECT id FROM criteria WHERE name = 'Alimentation'), 'Régime particulier'),
      ((SELECT id FROM criteria WHERE name = 'Niveau d''activité'), 'Sédentaire'),
      ((SELECT id FROM criteria WHERE name = 'Niveau d''activité'), 'Modérément actif'),
      ((SELECT id FROM criteria WHERE name = 'Niveau d''activité'), 'Très actif'),
      ((SELECT id FROM criteria WHERE name = 'Niveau d''activité'), 'Sportif régulier'),
      ((SELECT id FROM criteria WHERE name = 'Niveau d''activité'), 'Entraînement intensif'),
      ((SELECT id FROM criteria WHERE name = 'Tranche d''âge'), '18-25 ans'),
      ((SELECT id FROM criteria WHERE name = 'Tranche d''âge'), '26-35 ans'),
      ((SELECT id FROM criteria WHERE name = 'Tranche d''âge'), '36-45 ans'),
      ((SELECT id FROM criteria WHERE name = 'Tranche d''âge'), '46-55 ans'),
      ((SELECT id FROM criteria WHERE name = 'Tranche d''âge'), '56 ans et plus'),
      ((SELECT id FROM criteria WHERE name = 'Tabagisme'), 'Non-fumeur'),
      ((SELECT id FROM criteria WHERE name = 'Tabagisme'), 'Fumeur occasionnel'),
      ((SELECT id FROM criteria WHERE name = 'Tabagisme'), 'Fumeur régulier'),
      ((SELECT id FROM criteria WHERE name = 'Tabagisme'), 'Ex-fumeur'),
      ((SELECT id FROM criteria WHERE name = 'Allergies'), 'Aucune allergie connue'),
      ((SELECT id FROM criteria WHERE name = 'Allergies'), 'Pollen'),
      ((SELECT id FROM criteria WHERE name = 'Allergies'), 'Acariens'),
      ((SELECT id FROM criteria WHERE name = 'Allergies'), 'Animaux'),
      ((SELECT id FROM criteria WHERE name = 'Allergies'), 'Aliments spécifiques'),
      ((SELECT id FROM criteria WHERE name = 'Traitement'), 'Aucun traitement en cours'),
      ((SELECT id FROM criteria WHERE name = 'Traitement'), 'Médicaments oraux'),
      ((SELECT id FROM criteria WHERE name = 'Traitement'), 'Traitement topique'),
      ((SELECT id FROM criteria WHERE name = 'Traitement'), 'Traitement dermatologique'),
      ((SELECT id FROM criteria WHERE name = 'Traitement'), 'Chirurgie esthétique'),
      ((SELECT id FROM criteria WHERE name = 'Exposition à la pollution'), 'Environnement urbain dense'),
      ((SELECT id FROM criteria WHERE name = 'Exposition à la pollution'), 'Environnement industriel'),
      ((SELECT id FROM criteria WHERE name = 'Exposition à la pollution'), 'Environnement rural'),
      ((SELECT id FROM criteria WHERE name = 'Exposition à la pollution'), 'Exposition quotidienne'),
      ((SELECT id FROM criteria WHERE name = 'Exposition à la pollution'), 'Exposition occasionnelle'),
      ((SELECT id FROM criteria WHERE name = 'Objectif'), 'Hydratation'),
      ((SELECT id FROM criteria WHERE name = 'Objectif'), 'Anti-âge'),
      ((SELECT id FROM criteria WHERE name = 'Objectif'), 'Lutte contre l''acné'),
      ((SELECT id FROM criteria WHERE name = 'Objectif'), 'Éclat'),
      ((SELECT id FROM criteria WHERE name = 'Objectif'), 'Protection solaire')
  `.execute(trx);
});
