version: '3'

name: '2023-09-orleans-cda-projet2-staging'

services:
  api:
    image: no3ml3/yummycorn-api-staging:latest
    restart: always
    depends_on:
      database:
        condition: service_healthy
        restart: true
    env_file:
      - ./common.env
      - ./api.env
    volumes:
      - uploads:/app/uploads
    networks:
      - db
      - backend

  web:
    image: no3ml3/yummycorn-web-staging:latest
    env_file:
      - ./common.env
      - ./web.env
    volumes:
      - web-client-build:/app
    networks:
      - frontend

  nginx:
    image: nginx:1.21.3
    depends_on:
      - web
      - api
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - uploads:/uploads
    networks:
      - backend
      - frontend

  database:
    image: mysql:8.2.0
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-uuser', '-ppassword']
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s
    networks:
      - db

  migrations:
    image: no3ml3/yummycorn-migrations-staging:latest
    env_file:
      - ./common.env
      - ./api.env
    depends_on:
      database:
        condition: service_healthy
        restart: true
    networks:
      - db

volumes:
  web-client-build:
  uploads:

networks:
  frontend:
  backend:
  db:
