import express from 'express';

import { adminCocktailRouter } from './admin/admin-cocktail';
import { adminCommentRouter } from './admin/admin-comment';
import { adminGlassRouter } from './admin/admin-glass';
import { adminIngredientRouter } from './admin/admin-ingredient';
import { adminToppingRouter } from './admin/admin-topping';
import { adminUserRouter } from './admin/admin-user';
import { alcoholRouter } from './alcohol';
import { authRouter } from './auth';
import { cocktailRouter } from './cocktail';
import { commentRouter } from './comment';
import { favoriteRouter } from './favorite';
import { filterRouter } from './filter';
import { glass } from './glass';
import { ingredient } from './ingredient';
import { ratingRouter } from './rating';
import { topping } from './topping';
import { user } from './user';
import { virginRouter } from './virgin';

const router = express.Router();

router.use('/auth', authRouter);
router.use('/user', user);
router.use('/ingredient', ingredient);
router.use('/cocktail', cocktailRouter);
router.use('/virgin', virginRouter);
router.use('/comment', commentRouter);
router.use('/rating', ratingRouter);
router.use('/glass', glass);
router.use('/filter', filterRouter);
router.use('/topping', topping);
router.use('/favorite', favoriteRouter);
router.use('/alcohol', alcoholRouter);
router.use('/admin/cocktail', adminCocktailRouter);
router.use('/admin/comment', adminCommentRouter);
router.use('/admin/glass', adminGlassRouter);
router.use('/admin/ingredient', adminIngredientRouter);
router.use('/admin/topping', adminToppingRouter);
router.use('/admin/user', adminUserRouter);
export default router;
